<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ApplicationIcon Condition="Exists('icon.ico')">icon.ico</ApplicationIcon>
		<NoWarn>1701;1702;1591</NoWarn>
		<OutputPath>..\..\..\game\bin\managed</OutputPath>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<SentryDisableSourceGenerator>true</SentryDisableSourceGenerator>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sandbox.AppSystem\Sandbox.AppSystem.csproj" />
		<ProjectReference Include="..\..\Sandbox.Compiling\Sandbox.Compiling.csproj" />
		<ProjectReference Include="..\..\Sandbox.Engine\Sandbox.Engine.csproj" />
		<ProjectReference Include="..\..\Sandbox.Menu\Sandbox.Menu.csproj" />
	</ItemGroup>

</Project>
