using System.Globalization;
using System.Text;
using System.Threading;

namespace Editor;

/// <summary>
/// A list of cloud assets.
/// </summary>
public partial class CloudAssetBrowser : Widget, IBrowser
{
	/// <summary>
	/// Only show these asset types.
	/// </summary>
	public List<AssetType> FilterAssetTypes { get; protected set; }

	/// <summary>
	/// Internal asset list panel.
	/// </summary>
	protected AssetList AssetList;

	/// <inheritdoc cref="BaseItemWidget.MultiSelect"/>
	public bool MultiSelect
	{
		get => AssetList.MultiSelect;
		set => AssetList.MultiSelect = value;
	}

	public List<T> GetSelected<T>() => AssetList.Selection.OfType<T>().ToList();

	public string BaseQuery { get; private set; }
	public SearchWidget Search;

	ToolButton ViewMode;
	ToolButton OrderMode;
	ListHeader ListHeader;
	FilterBreadcrumb Breadcrumb;
	Button _updateAllBtn;
	bool _updatingAll;
	string lastSortColumn = "";
	bool lastSortAscending = true;

	/// <summary>
	/// Package has been clicked
	/// </summary>
	public Action<Package> OnPackageHighlight;

	/// <summary>
	/// Package has been selected (double click, or enter)
	/// </summary>
	public Action<Package> OnPackageSelected;

	/// <summary>
	/// Internal left side panel — navigation tree
	/// </summary>
	protected CloudLocations CloudLocations;

	/// <summary>
	/// Compact filter bar above the asset list — pill buttons for each available facet dimension.
	/// Populated from the facets returned by FetchPackages, no extra API calls required.
	/// </summary>
	CloudFilterBar FilterBar;

	public Action OnFolderOpened;

	/// <summary>
	/// Show files generated by asset compilation and other usually unuseful files.
	/// </summary>
	public bool ShowJunkFiles { get; set; }
	public bool HideNonAssets { get; set; }

	bool _showRecursive = false;

	/// <summary>
	/// If true, show all files in a flat view, if false, show files and folders like they would appear in Windows Explorer.
	/// </summary>
	public bool ShowRecursiveFiles
	{
		get => _showRecursive;
		set
		{
			if ( _showRecursive == value ) return;
			_showRecursive = value;

			UpdateAssetList();
			SaveSettings();
		}
	}

	/// <summary>
	/// View mode, i.e. thumbs, list or whatever else.
	/// </summary>
	public AssetListViewMode ViewModeType
	{
		get;
		set
		{
			field = value;

			AssetList.ViewMode = field;
			SaveSettings();

			if ( value == AssetListViewMode.List ) ViewMode.Icon = "view_headline";
			if ( value == AssetListViewMode.SmallIcons ) ViewMode.Icon = "apps";
			if ( value == AssetListViewMode.MediumIcons ) ViewMode.Icon = "grid_on";
			if ( value == AssetListViewMode.LargeIcons ) ViewMode.Icon = "grid_view";
		}
	}

	public static string DefaultView
	{
		get => EditorCookie.GetString( "CloudBrowser.DefaultView", "" );
		set => EditorCookie.SetString( "CloudBrowser.DefaultView", value );
	}

	string CurrentOrderMode = "rankweek";

	Task ResultsTask;

	bool IsLoading
	{
		get => field; set
		{
			field = value;
			Update();
		}
	}

	public CloudAssetBrowser( Widget parent ) : this( parent, null )
	{

	}

	public CloudAssetBrowser( Widget parent, List<AssetType> assetTypeFilters ) : base( parent )
	{
		MinimumSize = new( 100, 100 );

		Layout = Layout.Row();
		Layout.Spacing = 4;

		FilterAssetTypes = assetTypeFilters;

		ListHeader = new ListHeader( this, ["Name", "Author", "Date", "Type"] );
		ListHeader.OnColumnSelect += SortAssetList;
		ListHeader.OnColumnResize += () => AssetList?.Update();

		AssetList = new AssetList( this );
		AssetList.Browser = this;
		AssetList.OnViewModeChanged += () => SaveSettings();
		AssetList.OnHighlight = ( entries ) =>
		{
			var highlightedEntries = entries.ToList();
			var packages = highlightedEntries.OfType<PackageEntry>().ToList();

			if ( packages.Count == 1 && packages.Count == highlightedEntries.Count )
			{
				OnPackageHighlight?.Invoke( packages.First().Package );
			}
		};

		AssetList.OnPaintOverride = () =>
		{
			if ( IsLoading )
			{
				Paint.ClearBrush();
				Paint.SetPen( Theme.TextLight );
				Paint.DrawText( AssetList.LocalRect, "Searching...", TextFlag.Center );
			}
			else if ( !AssetList.Items.Any() )
			{
				Paint.ClearBrush();
				Paint.SetPen( Theme.TextLight );
				Paint.DrawText( AssetList.LocalRect, "No assets found", TextFlag.Center );
			}

			return false;
		};

		CloudLocations = new CloudLocations( this );
		CloudLocations.ActiveFilters.OnChanged = () =>
		{
			FilterBar?.RefreshPills();
			UpdateAssetList();
		};
		CloudLocations.OnFilterSelected = ( node ) =>
		{
			NavigateTo( node.Filter );
			Breadcrumb.SetPath( node );
			Search.PlaceholderText = string.IsNullOrEmpty( node.Filter )
				? "⌕  Search"
				: $"⌕  Search in {node.Label}";
		};

		// Left sidebar: collection search (seamlessly above) + nav tree
		var leftPanel = new Widget( this );
		leftPanel.Layout = Layout.Column();
		leftPanel.Layout.Spacing = 0;
		leftPanel.Layout.Margin = new Margin( 0, 0, 0, 0 );
		leftPanel.Layout.Add( CloudLocations, 1 );

		var body = new Widget( this );
		body.Layout = Layout.Column();

		// Nav bar: breadcrumb (left, stretch) + search (right)
		var navBar = new Widget( body );
		navBar.FixedHeight = 34;
		navBar.Layout = Layout.Row();
		navBar.Layout.Spacing = 6;
		navBar.Layout.Margin = new Margin( 6, 4, 8, 4 );

		Breadcrumb = new FilterBreadcrumb( NavigateTo, navBar );
		navBar.Layout.Add( Breadcrumb, 1 );

		_updateAllBtn = new Button.Clear( "Update All", "download" );
		_updateAllBtn.Visible = false;
		_updateAllBtn.MouseClick = () => _ = UpdateAllReferencedAsync();
		navBar.Layout.Add( _updateAllBtn );

		Search = new SearchWidget( navBar, false );
		Search.FixedHeight = Theme.ControlHeight;
		Search.FixedWidth = 200;
		Search.ValueChanged = () => UpdateAssetList();
		navBar.Layout.Add( Search );

		body.Layout.Add( navBar );

		// Filter bar: facet pills + order/view buttons
		FilterBar = new CloudFilterBar( CloudLocations.ActiveFilters, UpdateAssetList, body );
		ViewMode = FilterBar.ViewMode;
		OrderMode = FilterBar.OrderMode;
		body.Layout.Add( FilterBar );

		body.Layout.Add( ListHeader );
		body.Layout.Add( AssetList, 1 );

		var splitter = new Splitter( this );
		splitter.IsHorizontal = true;
		splitter.AddWidget( leftPanel );
		splitter.SetStretch( 0, 1 );
		splitter.AddWidget( body );
		splitter.SetStretch( 1, 5 );

		Layout.Add( splitter );

		ConfigureViewMode();
		RefreshCookies();
	}

	protected override void OnVisibilityChanged( bool visible )
	{
		base.OnVisibilityChanged( visible );

		if ( !visible )
			return;

		// Calling this here so that when the window is made visible the cookie
		// key gets set up correctly - when we add a new instance of the asset
		// browser, it requires its own unique key for settings.
		RefreshCookies();
	}

	private void RefreshCookies()
	{
		SettingsCookie = GetCookieKey();
		LoadSettings();

		UpdateAssetList();
	}

	private string GetCookieKey()
	{
		StringBuilder stringBuilder = new( "CloudBrowser" );

		if ( FilterAssetTypes != null )
			stringBuilder.Append( $".{string.Join( ",", FilterAssetTypes )}" );

		if ( Name != null )
			stringBuilder.Append( $".{Name.Replace( " ", "" )}" );

		return stringBuilder.ToString();
	}

	/// <summary>
	/// Directory, contents of which are currently being displayed.
	/// </summary>
	public LocalAssetBrowser.Location CurrentLocation { get; set; }

	CancellationTokenSource tokenSource;

	/// <summary>
	/// Update the list of displayed assets.
	/// </summary>
	public virtual void UpdateAssetList()
	{
		string query = $"{BaseQuery} {Search.Query}";
		if ( query.Contains( "@referenced" ) )
		{
			var searchValue = query.Replace( "@referenced", "" ).Trim();

			UpdateFromReferenced( searchValue );
		}
		else
		{
			ResultsTask = UpdateFromCloud( query );
		}
	}

	private void SortAssetList( string sortBy, bool ascending )
	{
		List<object> items;
		switch ( sortBy )
		{
			case "Name":
				items = AssetList.Items.OrderBy( x =>
				{
					if ( x is PackageEntry pe ) return pe.Package.Title;
					return "";
				} ).ToList();
				break;
			case "Author":
				items = AssetList.Items.OrderBy( x =>
				{
					if ( x is PackageEntry pe ) return pe.Package.Org.Title;
					return "";
				} ).ToList();
				break;
			case "Date":
				items = AssetList.Items.OrderBy( x =>
				{
					if ( x is PackageEntry pe ) return pe.Package.Updated.UtcTicks;
					return 0L;
				} ).ToList();
				break;
			case "Type":
				items = AssetList.Items.OrderBy( x =>
				{
					if ( x is PackageEntry pe ) return pe.Package.TypeName;
					return "";
				} ).ToList();
				break;
			default:
				items = AssetList.Items.ToList();
				break;
		}

		if ( !ascending )
		{
			items.Reverse();
		}
		AssetList.SetItems( items );

		lastSortColumn = sortBy;
		lastSortAscending = ascending;
	}

	/// <summary>
	/// Check if <paramref name="str"/> contains <paramref name="value"/>, ignoring case and white space.
	/// </summary>
	private static bool FuzzyContains( string str, string value )
	{
		return CultureInfo.InvariantCulture.CompareInfo.IndexOf( str, value, CompareOptions.IgnoreCase | CompareOptions.IgnoreSymbols ) >= 0;
	}

	void UpdateFromReferenced( string query )
	{
		var packages = AssetSystem.GetReferencedPackages();

		AssetList.Clear();

		foreach ( var package in packages.Where( x => FuzzyContains( x.Title, query ) ) )
		{
			if ( package.TypeName == "game" ) continue;
			string assetPath = package.GetMeta<string>( "PrimaryAsset" );
			var a = AssetSystem.FindByPath( assetPath );

			if ( a is null )
				continue;

			AssetList.AddItem( new PackageEntry( package ) );
		}
	}

	async Task UpdateFromCloud( string q )
	{
		IsLoading = true;

		AssetList.Clear();

		if ( FilterAssetTypes?.Count > 0 )
		{
			q += $" type:{GetAssetType( FilterAssetTypes.First().FileExtension )}";
		}

		var activeFilters = CloudLocations?.ActiveFilters;
		if ( activeFilters is { IsEmpty: false } )
		{
			q += $" {activeFilters.ToQueryString()}";
		}

		q += $" sort:{CurrentOrderMode}";
		q = q.Trim();

		await FetchPackages( q, 400, 0 );
	}

	string GetAssetType( string extension )
	{
		switch ( extension )
		{
			case "vmap":
				return "map";
			case "vmdl":
				return "model";
			case "vmat":
				return "material";
			default:
				return extension;
		}
	}

	string _lastQuery = "";
	int _lastTake = 0;
	int _lastSkip = 0;
	bool _lastQueryReachedEnd = false;
	async Task FetchPackages( string q, int take, int skip )
	{
		try
		{
			IsLoading = true;

			tokenSource?.Cancel();
			tokenSource = new CancellationTokenSource();

			if ( !IsValid )
				return;

			var token = tokenSource.Token;
			var found = await Package.FindAsync( q, take, skip, token );

			if ( !IsValid || token.IsCancellationRequested || found == null )
				return;

			_lastQuery = q;
			_lastTake = take;
			_lastSkip = skip;
			_lastQueryReachedEnd = found.Packages.Length < take;

			// Populate the filter bar from the first page's facet data (no extra API call needed)
			if ( skip == 0 )
				FilterBar?.SetFacets( found.Facets );

			if ( found.Packages.Length == 0 )
				return;

			//
			// Add them all to the list
			//
			foreach ( var item in found.Packages )
			{
				if ( item.TypeName == "game" || item.TypeName == "library" ) continue;
				AssetList.AddItem( new PackageEntry( item ) );
			}

			if ( !string.IsNullOrEmpty( lastSortColumn ) )
			{
				SortAssetList( lastSortColumn, lastSortAscending );
			}

			//
			// Get order modes
			//
			OrderMode.MouseLeftPress = () =>
			{
				var menu = new ContextMenu( this );

				foreach ( var orderMode in found.Orders )
				{
					var option = menu.AddOption( orderMode.Title, orderMode.Icon, () =>
					{
						CurrentOrderMode = orderMode.Name;
						OrderMode.Icon = orderMode.Icon;

						UpdateAssetList();
					} );

					option.Checkable = true;
					option.Checked = orderMode.Name == CurrentOrderMode;
				}

				menu.OpenAt( OrderMode.ScreenRect.BottomLeft, false );
			};
		}
		finally
		{
			IsLoading = false;
		}
	}

	/// <summary>
	/// Navigate to a filter query — used by both tree selection and breadcrumb clicks.
	/// Breadcrumb clicks truncate the path, so we reset the breadcrumb and let the next
	/// tree selection rebuild it.
	/// </summary>
	void NavigateTo( string filter )
	{
		BaseQuery = filter;

		// Show "Update All" only on the Referenced tab
		if ( _updateAllBtn.IsValid() )
		{
			_updateAllBtn.Visible = filter == "@referenced";
			_updateAllBtn.Text = "Update All";
			_updateAllBtn.Enabled = true;
			_updatingAll = false;
		}

		CloudLocations?.ActiveFilters.Clear(); // facet selections don't carry over on context change
		FilterBar?.ClearFacets();             // hide stale pills; repopulated by next FetchPackages
		UpdateAssetList();
	}

	async Task UpdateAllReferencedAsync()
	{
		if ( _updatingAll || !_updateAllBtn.IsValid() ) return;
		_updatingAll = true;
		_updateAllBtn.Enabled = false;
		_updateAllBtn.Text = "Checking...";

		var packages = AssetSystem.GetReferencedPackages();
		var toUpdate = new List<string>();

		foreach ( var pkg in packages )
		{
			var local = AssetSystem.GetInstalledRevision( pkg.FullIdent );
			if ( local is null ) continue;

			var versions = await Package.FetchVersions( pkg.FullIdent );
			var latest = versions?.FirstOrDefault();

			if ( latest is not null && latest.VersionId != local.VersionId )
				toUpdate.Add( pkg.FullIdent );
		}

		if ( !IsValid ) return;

		if ( toUpdate.Count == 0 )
		{
			_updateAllBtn.Text = "Up to Date";
			_updateAllBtn.Enabled = true;
			_updatingAll = false;
			return;
		}

		int done = 0;
		foreach ( var ident in toUpdate )
		{
			if ( !IsValid ) return;
			_updateAllBtn.Text = $"Updating {++done}/{toUpdate.Count}...";
			await AssetSystem.InstallAsync( ident, false );
		}

		if ( !IsValid ) return;

		_updatingAll = false;
		_updateAllBtn.Text = "Update All";
		_updateAllBtn.Enabled = true;
		UpdateAssetList();
	}

	public void LoadMore()
	{
		if ( _lastQueryReachedEnd || (BaseQuery?.StartsWith( "@referenced" ) ?? false) )
			return;
		var skip = _lastSkip + _lastTake;
		_ = FetchPackages( _lastQuery, _lastTake, skip );
	}

	protected override void OnKeyPress( KeyEvent e )
	{
		if ( e.Key == KeyCode.F5 )
		{
			UpdateAssetList();
			return;
		}

		base.OnKeyPress( e );
	}

	string SettingsCookie { get; set; }
	bool SuppressSaveSettings { get; set; }

	/// <summary>
	/// Load settings saved by <see cref="SaveSettings"/>.
	/// </summary>
	public virtual void LoadSettings()
	{
		if ( string.IsNullOrEmpty( SettingsCookie ) )
			return;

		SuppressSaveSettings = true;

		ViewModeType = (AssetListViewMode)ProjectCookie.Get<int>( $"{SettingsCookie}.ViewMode", (int)AssetList.ViewMode );
		ShowJunkFiles = ProjectCookie.Get<bool>( $"{SettingsCookie}.ShowJunkFiles", ShowJunkFiles );
		HideNonAssets = ProjectCookie.Get<bool>( $"{SettingsCookie}.HideNonAssets", HideNonAssets );
		ShowRecursiveFiles = ProjectCookie.Get<bool>( $"{SettingsCookie}.ShowRecursiveFiles", ShowRecursiveFiles );

		SuppressSaveSettings = false;
	}

	/// <summary>
	/// Save asset browser user settings, such as view mode, <see cref="ShowJunkFiles"/> and <see cref="ShowRecursiveFiles"/>.
	/// The save slot is separate for each asset browser filter combination set in the constructor.
	/// </summary>
	public virtual void SaveSettings()
	{
		if ( string.IsNullOrEmpty( SettingsCookie ) )
			return;

		if ( SuppressSaveSettings )
			return;

		ProjectCookie.Set<int>( $"{SettingsCookie}.ViewMode", (int)AssetList.ViewMode );
		ProjectCookie.Set<bool>( $"{SettingsCookie}.ShowJunkFiles", ShowJunkFiles );
		ProjectCookie.Set<bool>( $"{SettingsCookie}.HideNonAssets", HideNonAssets );
		ProjectCookie.Set<bool>( $"{SettingsCookie}.ShowRecursiveFiles", ShowRecursiveFiles );
	}

	/// <summary>
	/// Focus on this package, make it selected, when results are recieved
	/// </summary>
	public async void FocusOnPackage( Package package, bool skipEvents = false )
	{
		if ( package is null ) return;

		await ResultsTask;
		await Task.Yield();

		var entry = AssetList.Items.OfType<PackageEntry>().Where( x => x.Package.Ident == package.Ident ).FirstOrDefault();
		AssetList.SelectItem( entry, skipEvents: skipEvents );
		AssetList.ScrollTo( entry );
	}

	public void AddPin( string filter )
	{
		// TODO
		throw new NotImplementedException();
	}
}

