<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Shared\LaunchShared.projitems" Label="Shared" />

	<PropertyGroup>
		<VersionPrefix>1.0.1</VersionPrefix>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<AssemblyName>sbox-profiler</AssemblyName>

		<GenerateDependencyFile>true</GenerateDependencyFile>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
		<GenerateRuntimeConfigDevFile>false</GenerateRuntimeConfigDevFile>
		<PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<LangVersion>14</LangVersion>
		<OutputPath>..\..\..\game\bin\managed</OutputPath>
		<OutputType>winexe</OutputType>
		<StartupObject>Sandbox.Program</StartupObject>
		<DebugType>embedded</DebugType>
		<ApplicationIcon Condition="Exists('sbox-profiler.ico')">sbox-profiler.ico</ApplicationIcon>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.21" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sandbox.Engine\Sandbox.Engine.csproj" />
	</ItemGroup>

</Project>
